num_workers: 16
batch_size: 1
cuda: 0
weight_name: "latest" # Used during resume, select with model to load from [miou, macc, acc..., latest]
enable_cudnn: True
checkpoint_dir: "/media/bobo/domek/PycharmProjects/PointNet++/outputs/benchmark/benchmark-pointnet2_charlesssg-20210406_120711" # "{your_path}/outputs/2020-01-28/11-04-13"
model_name: pointnet2_charlesssg
precompute_multi_scale: True # Compute multiscate features on cpu for faster training / inference
enable_dropout: False
voting_runs: 1
defaults:
  - visualization: default

tracker_options: # Extra options for the tracker
  full_res: False
  make_submission: True

hydra:
  run:
    dir: ${checkpoint_dir}/eval/${now:%Y-%m-%d_%H-%M-%S}
